openapi: 3.0.2
info:
  title: OpenAPI Course
  description: Specification for OpenAPI Course
  termsOfService: http://example.com/terms/
  contact:
    name: John Thompson
    url: https://springframework.guru
    email: john@springframework.guru
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
- url: https://dev.example.com
  description: Development Server
- url: https://qa.example.com 
  description: Quality Assurance
- url: https://prod.example.com
  description: Production Server
paths: 
  /v1/customers:
    get:
      summary: List of Customers
      description: Get a list all customers in the system.
      tags:
        - Customers
      operationId: listCustomerV1
      parameters:
        - $ref: "#/components/parameters/PageNumberPara"
        - $ref: "#/components/parameters/PageSizePara"
      responses:
        '200':
          description: List of Customers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerPagedList"          
    post:
      summary: New Customer
      description: Create a new customer
      tags:
        - Customer
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
      responses:
        '201':
          description: Customer Created


  /v1/customers/{customerID}:
    get:
      summary: Get Customer By ID
      description: Get a single **Customer** by it's Id value.
      tags:
        - Customers
      operationId: getCustomerByIdV1
      parameters:
        - name: customerID
          in: path
          description: Customer ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Found Customer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"

  /v1/beers/{beerID}:
    get:
      summary: Get Beer By ID
      description: Get a single **Beer** by it's Id value
      tags:
        - Beers
      operationId: getBeersByIdV1
      parameters:
        - name: beerID
          in: path
          description: Beer ID
          required: true
          schema:
            type: string
            format: uiid
      responses:
        '200':
          description: Found Beer ID
          content:
            application/json:
                schema:
                  $ref: "#/components/schemas/BeersObject"


  /v1/beers:
    get:
      summary: List of Beers
      description: Get a list all beers in the system.
      tags:
        - Beers
      operationId: listBeersV1
      parameters:
        - $ref: "#/components/parameters/PageNumberPara"
        - $ref: "#/components/parameters/PageSizePara"
        

      responses:
        '200':
          description: List of Beers
          content:
            application/jason:
              schema:
                $ref: "#/components/schemas/BeerPagedList"
        '404':
          description: Not Beers found
  
components: 
  schemas:
    Address:
      type: object
      properties:
        line1:
          type: string
          example: Straße 32
        city:
          type: string
          example: Graz
        stateCode:
          type: string
          minLength: 2
          maxLength: 4
          enum: [STMK, NO, OB, KNT, VIE]
        zipCode:
          type: string
          example: 8020
    Customer:
      type: object
      description: customer object
      properties:
        id:
          type: string
          format: uiid
        firstName:
          type: string
          minLength: 2
          maxLength: 100
          example: Max
        lastName:
          type: string
          minLength: 2
          maxLength: 100
          example: Musterman
        adress:
          $ref: "#/components/schemas/Address"
    CustomerList:
      type: array
      minItems: 1
      maxItems: 100
      description: List of Customers
      items: 
        $ref: "#/components/schemas/Customer"
    Brewery:
      type: object
      properties:
        name:
          type: string
          example: Brauunion
        location:
          type: string
          example: Puntigam
    BeersObject:
      type: object
      properties:
        beerName:
          type: string
        variety:
          type: string
          enum: [ALE, PALE_ALE, IPA, WHEAT, LAGER]
        price:
          type: number
          format: float
          example: 3.5
        quantity:
          type: integer
          format: int32
          example: 2
        brewery:
          $ref: "#/components/schemas/Brewery"
    BeersList:
      type: array
      minItems: 1
      maxItems: 100
      items:
        $ref: "#/components/schemas/BeersObject"
    BeerPagedList:
      type: object
      allOf:
        - $ref: "#/components/schemas/PagedResponse"
      properties:
        content:
          $ref: "#/components/schemas/BeersList"
    CustomerPagedList:
      type: object
      allOf:
        - $ref: "#/components/schemas/PagedResponse"
      properties:
        content:
          $ref: "#/components/schemas/CustomerList"   
    PagedResponse:
      type: object
      properties:
        pageable:
          $ref: '#/components/schemas/PagedResponse_pageable'
        totalPages:
          type: integer
          format: int32
        last:
          type: boolean
        totalElements:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        number:
          type: integer
          format: int32
        numberOfElements:
          type: integer
          format: int32
        sort:
          $ref: '#/components/schemas/PagedResponse_pageable_sort'
        first:
          type: boolean
    PagedResponse_pageable_sort:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean   
    PagedResponse_pageable:
      type: object
      properties:
        sort:
          $ref: '#/components/schemas/PagedResponse_pageable_sort'
        offset:
          type: integer
          format: int32
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean
          
  parameters:
    PageNumberPara:
      name: pageNumber
      in: query
      description: Page Number
      schema:
        type: integer
        format: int32
        default: 1  
    PageSizePara:
      name: pageSize
      in: query
      description: Page Size
      required: false
      schema:
        type: integer
        format: int32
        default: 25

            

                          


                    